version: '3.9'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zk-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: broker-kafka1
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk-kafka:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  #broker2:
  #  image: confluentinc/cp-kafka:7.6.0
  #  container_name: broker-kafka2
  #  ports:
  #    - '9192:9192'
  #  environment:
  #    KAFKA_BROKER_ID: 2
  #    KAFKA_ZOOKEEPER_CONNECT: zk-kafka:2181
  #    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-kafka2:29192,PLAINTEXT_HOST://localhost:9192
  #    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  #  depends_on:
  #    - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    ports:
      - 8085:8085
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker-kafka1:29092 #,PLAINTEXT://broker-kafka2:29192
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8085

      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
    depends_on:
      - broker1
      #- broker2

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - '8082:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local-docker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-kafka1:29092 #,broker-kafka2:29192
      KAFKA_CLUSTERS_0_ZOOKEEPER: zk-kafka:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8085
    depends_on:
      - broker1
      #- broker2
      - zookeeper
      - schema-registry
